name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=algolia&hide_title=false
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top-langs card
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=algolia&layout=compact
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate hexgridspiral pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=hexgridspiral
          path: profile/hexgridspiral.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate adventofcode pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=adventofcode
          path: profile/adventofcode.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate algolab-tutorial pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=algolab-tutorial
          path: profile/algolab-tutorial.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate migrate-from-google-play-music pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=migrate-from-google-play-music
          path: profile/migrate-from-google-play-music.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Brotkeys.js pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=Brotkeys.js
          path: profile/Brotkeys.js.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate eth-cv pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=eth-cv
          path: profile/eth-cv.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate znap pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=znap
          path: profile/znap.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate shiverbot pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=shiverbot
          path: profile/shiverbot.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate conrod-howto pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=conrod-howto
          path: profile/conrod-howto.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate cevi-versand pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=cevi-versand
          path: profile/cevi-versand.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate mineDeeper pin
        uses: readme-tools/github-readme-stats-action@699af1ef2dba605a3600fad2a6575e9f81b37cb8
        with:
          card: pin
          options: username=${{ github.repository_owner }}&theme=algolia&repo=mineDeeper
          path: profile/mineDeeper.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push

